### ISSUE TITLE
Tracking: Porting examples from `ethers-rs`

### ISSUE THREAD

**Issue by yash-atreya** [alloy-rs/core#560]
### Component

Other (please provide more details)

### Describe the feature you would like

This is a tracking issue for porting examples from ethers to alloy.

### Examples
---
- [ ] Address book
- [ ] Anvil
    - [ ] Boot anvil
    - [ ] Deploy contracts
    - [ ] Fork
    - [ ] Testing
- [ ] Big numbers
    - [ ] Comparison and equivalence
    - [ ] Conversion
    - [ ] Creating Instances
    - [ ] Math operations
    - [ ] Utilities
- [ ] Contracts
    - [ ] Abigen
    - [ ] Compile
    - [ ] Creating Instances
    - [ ] Deploy Anvil
    - [ ] Deploy from ABI and bytecode
    - [ ] Deploy Moonbeam
    - [ ] Events
    - [ ] Events with meta
    - [ ] Methods
- [ ] Events
  - [ ] Logs and filtering
  - [ ] Solidity topics
- [ ] Middleware
  - [ ] Builder
  - [ ] Create custom middleware
  - [ ] Gas escalator
  - [ ] Gas oracle
  - [ ] Nonce manager
  - [ ] Policy
  - [ ] Signer
  - [ ] Time lag
  - [ ] Transformer
- [ ] Providers
  - [ ] Http
  - [ ] IPC
  - [ ] Mock 
  - [ ] Quorum
  - [ ] Retry
  - [ ] RW
  - [ ] WS
- [ ] Queries
  - [ ] Blocks
  - [ ] Contracts
  - [ ] Events
  - [ ] Paginated logs
  - [ ] UniswapV2 pair
  - [ ] Transactions
- [ ] Subscriptions
  - [ ] Watch blocks
  - [ ] Subscribe events by type
  - [ ] Subscribe logs
- [ ] Transactions
  - [ ] Call override
  - [ ] Create raw transaction
  - [ ] Create typed transaction
  - [ ] Decode input
  - [ ] EIP-1559
  - [ ] ENS
  - [ ] Estimate gas
  - [ ] Get gas price
  - [ ] Get gas price USD
  - [ ] Remove liquidity
  - [ ] Set gas for a transaction
  - [ ] Send raw transaction
  - [ ] Send typed transaction
  - [ ] Trace
  - [ ] Transaction receipt
  - [ ] Transaction status
  - [ ] Transfer ETH
  - [ ] Transfer ERC20 token
- [ ] Wallets
  - [ ] Mnemonic
  - [ ] Ledger
  - [ ] Local
  - [ ] Permit hash
  - [ ] Sign message
  - [ ] Trezor
  - [ ] Yubi
